const locations = [
  {
    id: 1,
    locationName: "דרום ירושלים : מגזר יהודי בלבד",
    name: "ליאור דשקותאי",
    mail: "liordashko@gmail.com",
    lat: 31.7683,
    lng: 35.2137,
    placeId: "ChIJQ6qq6jRiMRAREq9jDV-Ub9Y", 
  },
  {
    id: 2,
    locationName: "צפון מזרח ירושלים : מגזר ערבי בלבד",
    name: "עסאם ומהדי",
    mail: "מהדי: mahdi.decart@gmail.com, עסאם: isam.decart@gmail.com",
    lat: 31.8133,
    lng: 35.2425,
    placeId: "ChIJ6y7kBFdiMRAREq9jDV-Ub9Y", 
  },
  {
    id: 3,
    locationName: "באקה אל-גרבייה והסביבה",
    name: "בוסינה ורביע",
    mail: "nextengi.bakat@gmail.com, bosenaward@gmail.com",
    lat: 32.3151,
    lng: 35.0424,
    placeId: "ChIJUyyU-Nt5FxURrxHpyZTUX8c", 
  },
  {
    id: 4,
    locationName: "דרום המשולש : מגזר ערבי בלבד",
    name: "לובנא ומנקיד",
    mail: "lulu8126@gmail.com",
    lat: 32.2837,
    lng: 35.0377,
    placeId: "ChIJt8SyWRw1NRUR1cA7oaDJaaE", 
  },
  {
    id: 5,
    locationName: "נצרת והסביבה : מגזר ערבי בלבד",
    name: "אחמד אבוליל",
    mail: "ahmad@wiseinfo.biz",
    lat: 32.6996,
    lng: 35.3035,
    placeId: "ChIJvVQH9F8CNRUROb6F4wP8Dzc", 
  },
  {
    id: 6,
    locationName: "טמרה, שפרעם, אעבלין ויישובי המגזר הבדואי",
    name: "מועאד",
    mail: "moaadsabtan@gmail.com",
    lat: 32.8522,
    lng: 35.1833,
    placeId: "ChIJRb8NsQz9NxUR3hEU3Ttt8AI", 
  },
  {
    id: 7,
    locationName: "הגליל: יישובי המגזר הדרוזי",
    name: "אמיר ולובנא חביש",
    mail: "hbaishlubna@gmail.com",
    lat: 32.9634,
    lng: 35.3128,
    placeId: "ChIJJfjHTx2fNBURFoXBXc00Dk8", 
  },
  {
    id: 8,
    locationName: "כרמיאל והסביבה",
    name: "אשרף וזהווה סגיר",
    mail: "ash1975majd@gmail.com",
    lat: 32.9184,
    lng: 35.2907,
    placeId: "ChIJg8yHg23ZNBURQuwVMIurM6o", 
  },
  {
    id: 9,
    locationName: "חיפה, סחנין והסביבה - מגזר נוצרי ומוסלמי",
    name: "וואסיף ורים חביב",
    mail: "lareen.for.studying@gmail.com",
    lat: 32.794,
    lng: 34.9896,
    placeId: "ChIJQwTTDeoLHRUR_7YlJ3t7SUw", 
  },
  {
    id: 10,
    locationName: 'צפון המשולש : מגזר ערבי בלבד (ואדי עארה)',
    name: "עביר יונס",
    mail: "lareen.for.studying@gmail.com",
    lat: 32.5035,
    lng: 35.0195,
    placeId: "ChIJS4K47Sx1NRURwtZayaxOlnY", 
  },
  {
    id: 11,
    locationName: "כפר סבא והסביבה : מגזר יהודי",
    name: "איתי שוסברגר",
    mail: "ishosberger@gmail.com",
    lat: 32.1749,
    lng: 34.9075,
    placeId: "ChIJW3pUk19OHRURl67Z7s1AoZc", 
  },
  {
    id: 12,
    locationName: 'קריית אונו והסביבה : מגזר יהודי רק לחוגים ולא בבתי הספר',
    name: "דן לרנר",
    mail: "danlerner@walla.com",
    lat: 32.0506,
    lng: 34.8617,
    placeId: "ChIJ8VKn9dRLHRURri70zHsPOMU", 
  },
  {
    id: 13,
    locationName: "מגדל העמק, קרית טבעון, רמת ישי והסביבה",
    name: "אביהו צור",
    mail: "avihutagel@gmail.com",
    lat: 32.6793,
    lng: 35.2441,
    placeId: "ChIJz9MlbvXBMBURo7yRoYogAF8", 
  },
  {
    id: 14,
    locationName: "פרדס חנה-כרכור והסביבה",
    name: "גל אוחנה",
    mail: "Nextengi.harish@gmail.com",
    lat: 32.4756,
    lng: 34.9753,
    placeId: "ChIJ9XyFwSx0NRURrDCICoVoQdE", 
  },
  {
    id: 15,
    locationName: "פתח תקווה וראש העין",
    name: "אבי פורשט (קבלן משנה)",
    mail: "ohanagal111@gmail.com",
    lat: 32.084,
    lng: 34.8872,
    placeId: "ChIJy1ZLNJxOHRURmPH3abDoPp8", 
  },
  {
    id: 16,
    locationName: "באר שבע: מגזר יהודי",
    name: "בנימין שוקרון",
    mail: "nextengi.rosh@gmail.com",
    lat: 31.252,
    lng: 34.7915,
    placeId: "ChIJq8xq2MM0AhURlXDiH0Whj8E", 
  },
  {
    id: 17,
    locationName: "נהריה ועכו: מגזר יהודי",
    name: "ענבל ברנשטיין",
    mail: "nextengi.galilm@gmail.com",
    lat: 33.0079,
    lng: 35.0945,
    placeId: "ChIJ0y_wAYfXMBURTwTz08OPgtY", 
  },
  {
    id: 18,
    locationName: "אשקלון וקרית גת",
    name: "יהודה ואקנין",
    mail: "nextengi.ashkelon@gmail.com",
    lat: 31.6688,
    lng: 34.5743,
    placeId: "ChIJWSv1zttkAhUR32ZryYRZz98", 
  },
  {
    id: 19,
    locationName: "אריאל והשומרון",
    name: "מוטי ושירן זיגדון",
    mail: "yehudavaknin8@gmail.com",
    lat: 32.1049,
    lng: 35.1809,
    placeId: "ChIJdWZw2PlMAxURVb2jZjVXJvA", 
  },
  {
    id: 20,
    locationName: "חדרה והסביבה",
    name: "עדיאל ומירב בארי",
    mail: "nextengi.shomron@gmail.com",
    lat: 32.434,
    lng: 34.9195,
    placeId: "ChIJN_IkTwh0NRURkKvDpk0pXvc", 
  },
  {
    id: 21,
    locationName: "אשדוד: מגזר יהודי",
    name: "יצחק עובדיה",
    mail: "adielb@gmail.com",
    lat: 31.8014,
    lng: 34.6435,
    placeId: "ChIJb1IQTDVRAhURowQ15v-XY6U", 
  },
  {
    id: 22,
    locationName: "רחובות: מגזר יהודי",
    name: "עוזי דגן",
    mail: "ozidan@013net.net",
    lat: 31.8948,
    lng: 34.8113,
    placeId: "ChIJHSnP8zlLHRURddOKDr7KAYs", 
  },
  {
    id: 23,
    locationName: "ראשון לציון: מגזר יהודי",
    name: "יואב אבוקרט",
    mail: "itzhakovad@gmail.com",
    lat: 31.972,
    lng: 34.7925,
    placeId: "ChIJNc5OfAFKHRURoU6Cf44H5Zc", 
  },
  {
    id: 24,
    locationName: "נתניה: מגזר יהודי",
    name: "חיים דמרי",
    mail: "nextengi.yoav1@gmail.com",
    lat: 32.3215,
    lng: 34.8532,
    placeId: "ChIJWTgIlWpTHRUR77gZ6mJIoOs", 
  },
  {
    id: 25,
    locationName: "רעננה, הרצליה והסביבה: מגזר יהודי",
    name: "אייל מלמד",
    mail: "nextengi.raanana@gmail.com",
    lat: 32.1848,
    lng: 34.8712,
    placeId: "ChIJrcytrcNPHRURgCmEsBq3O2A", 
  },
  {
    id: 26,
    locationName: "ירושלים והסביבה: מגזר יהודי",
    name: "יהודה קזז",
    mail: "yehuda@dameri.co.il",
    lat: 31.7683,
    lng: 35.2137,
    placeId: "ChIJQ6qq6jRiMRAREq9jDV-Ub9Y", 
  },
  {
    id: 27,
    locationName: "מודיעין והסביבה: מגזר יהודי",
    name: "ירון משה",
    mail: "nextengi.yarom@gmail.com",
    lat: 31.8996,
    lng: 35.0073,
    placeId: "ChIJNVbRexnTMBUR57nkAfH7Bac", 
  },
  {
    id: 28,
    locationName: "ירושלים: מגזר חרדי",
    name: "שלום עובדיה",
    mail: "shalomovadia11@gmail.com",
    lat: 31.7683,
    lng: 35.2137,
    placeId: "ChIJQ6qq6jRiMRAREq9jDV-Ub9Y", 
  }
];
export default locations;
