server {
    listen 80;
    server_name nextengineers.co.il www.nextengineers.co.il;

    # Main site
    location / {
        proxy_pass https://www.nextengineers.co.il;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Branch site
    location /branch/ {
        proxy_pass http://localhost:5173/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
